---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgeo-v3
spec:
  selector:
    matchLabels:
      app: sgeo-v3
  replicas: 1
  template:
    metadata:
      labels:
        app: sgeo-v3
    spec:
      containers:
        - name: sgeo-v3
          image: sgeo-v3:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: geo
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: sgeo-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: sgeo-v3
  type: NodePort